# Generated by Django 5.0.6 on 2024-07-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_appmodel_choose_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgg', models.ImageField(blank=True, null=True, upload_to='images')),
                ('prodname', models.TextField()),
                ('prodprice', models.TextField()),
            ],
        ),
    ]
