# Generated by Django 5.0.6 on 2024-07-23 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_submodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='submodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.appmodel'),
        ),
    ]
