# Generated by Django 5.0.6 on 2024-07-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_signupmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='submodel',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='submodel',
            name='imgone',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='submodel',
            name='imgtwo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
