# Generated by Django 5.0.6 on 2024-07-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_submodel_desc_submodel_imgone_submodel_imgtwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='submodel',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
