# Generated by Django 5.0.6 on 2024-07-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_submodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='appmodel',
            name='category',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='submodel',
            name='category',
            field=models.TextField(null=True),
        ),
    ]
